stages:
  - check
  - release

variables:
  CARGO_TERM_COLOR: always
  CARGO_TARGET_DIR: target

checks:
  stage: check
  image: rust:1
  before_script:
    - rustup component add rustfmt clippy
    - cargo fetch --locked
  script:
    - cargo fmt --check
    - cargo check --locked
    - cargo clippy --locked
    - cargo test --locked
  only:
    refs:
      - merge_requests
      - main
      - /^v.*$/

publish:
  stage: release
  image: rust:1
  script:
    - cargo publish --locked --no-verify
  only:
    refs:
      - /^v.*$/

release:
  stage: release
  image: alpine
  variables:
    GLAB_ENABLE_CI_AUTOLOGIN: "true"
    GIT_DEPTH: 0
  needs:
    - job: publish
  before_script:
    - apk update
    - apk install git-cliff glab
  script:
    - git-cliff --latest --output=release-notes.md
    - glab release create "$CI_COMMIT_TAG" --name "$CI_COMMIT_TAG" --notes-file release-notes.md --ref "$CI_COMMIT_SHA"
  only:
    refs:
      - /^v.*$/
