name: ci

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_TARGET_DIR: target

jobs:
  checks_on_commit:
    runs-on: codeberg-medium-lazy
    container:
      image: rust:1

    steps:
      - name: Checkout
        run: |
          git init .
          git remote add origin "${FORGEJO_SERVER_URL}/${FORGEJO_REPOSITORY}.git"
          git fetch --depth 1 origin "${FORGEJO_REF:-${GITHUB_SHA}}"
          git checkout --detach FETCH_HEAD

      - name: Dependencies
        run: |
          rustup component add rustfmt clippy
          cargo fetch --locked

      - name: Check formatting
        run: |
          cargo fmt --check

      - name: Check errors and common mistakes
        run: |
          cargo check --locked
          cargo clippy --locked

      - name: Check tests
        run: cargo test --locked
