name: release

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always
  CARGO_TARGET_DIR: target

jobs:
  release:
    runs-on: codeberg-small
    container:
      image: rust:1

    steps:
      - name: Actions runtime
        run: |
          apt-get update
          apt-get install nodejs -y

      - name: Checkout
        uses: actions/checkout@v7

      - name: Publish crate
        run: |
          cargo build --release --locked
          cargo publish --locked
          install -D target/release/dbcrab dist/dbcrab

      - name: Create release
        uses: actions/forgejo-release@v2.13.1
        with:
          direction: upload
          release-dir: dist
          override: true
          release-notes-assistant: true
